### ISSUE TITLE
Where is checkpoint.pt?

### ISSUE THREAD

**Issue by ghost** [KingJamesSong/PDETraversal#3]
Hello,

I dont see where you included your pretrained model checkpoint.pt? Can you upload it?

Thanks!

**Comment by KingJamesSong** [comment]
Hi, Thanks for your interest in our work!

Since our work relies on pre-trained VAEs/GANS, it is easy to train the model and get the results so we do not provide checkpoints.

For example, to get the results on AnimeFace with SNGAN, You need to run anime.sh to first train the model.

Feel free to ask any further questions.
